# Generated by Django 2.0.8 on 2018-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('flickr_id', models.CharField(max_length=30)),
                ('name', models.CharField(default=None, max_length=255)),
                ('member_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
