# Generated by Django 2.0.8 on 2018-08-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flick.Groups')),
            ],
            options={
                'db_table': 'group_photos',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('flickr_id', models.CharField(max_length=30)),
                ('owner', models.CharField(default=None, max_length=255)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('comments_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='PhotoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=50)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flick.Photos')),
            ],
            options={
                'db_table': 'photo_tags',
            },
        ),
        migrations.CreateModel(
            name='PhotoUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True)),
                ('size', models.CharField(max_length=30)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flick.Photos')),
            ],
            options={
                'db_table': 'photo_urls',
            },
        ),
        migrations.AddField(
            model_name='groupphotos',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flick.Photos'),
        ),
    ]
