# Generated by Django 2.0.8 on 2018-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0002_auto_20180814_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='owner',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
