# Generated by Django 2.0.8 on 2018-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0003_auto_20180814_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
