# Generated by Django 2.0.8 on 2018-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0004_photos_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototags',
            name='tag',
            field=models.TextField(blank=True),
        ),
    ]
