# Generated by Django 2.0.8 on 2018-08-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0005_auto_20180814_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototags',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='flick.Photos'),
        ),
        migrations.AlterField(
            model_name='photourls',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='flick.Photos'),
        ),
    ]
