# Generated by Django 2.0.8 on 2018-08-15 18:35

from django.db import migrations, models
import flick.models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0006_auto_20180814_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='icon',
            field=models.ImageField(null=True, upload_to=flick.models.get_image_path),
        ),
    ]
