# Generated by Django 2.0.8 on 2018-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0008_auto_20180815_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='icon',
            field=models.ImageField(null=True, upload_to='get_image_path'),
        ),
    ]
