# Generated by Django 2.0.8 on 2018-08-15 18:52

from django.db import migrations, models
import flick.models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0009_auto_20180815_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='icon',
            field=models.ImageField(null=True, upload_to=flick.models.get_image_path),
        ),
    ]
