# Generated by Django 2.0.8 on 2018-08-15 19:18

from django.db import migrations, models
import flick.models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0010_auto_20180815_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photourls',
            name='photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to=flick.models.get_image_path),
        ),
        migrations.DeleteModel(
            name='PhotoUrls',
        ),
    ]
