# Generated by Django 2.0.8 on 2018-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0013_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCelery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'test_celery',
            },
        ),
    ]
