# Generated by Django 2.0.8 on 2018-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0014_testcelery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCelery',
        ),
        migrations.AddField(
            model_name='photos',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photos',
            name='farm',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='secret',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='server',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
